### ISSUE TITLE
Not Compatible With Firefox Quantum

### ISSUE THREAD

**Issue by karthicraghupathi** [todvora/wsdl-browser#1]
Hello! I stumbled upon the WSDL Preview add on for Firefox. Looks like a great extension that I could really use.

However I get a message saying this add on is not compatible with Firefox Quantum.

Just checking in to see if you have any plans to make it work with the latest version of Firefox.

Thanks!

**Comment by todvora** [comment]
Hi @karthicraghupathi,
Sorry, I have no plans to update this extension. But I will be more than glad to accept any pull request if you have some experience with the new format of FF extensions. 

IIRC the SoapUI has similar functionality built-in - they can browse a WSDL file and export it to the HTML similar to this extension: https://www.soapui.org/soap-and-wsdl/working-with-wsdls.html

Or you can use directly the original XSLT transformation in-browser here: http://tomi.vanek.sk/

Best regards,
Tomas

**Comment by karthicraghupathi** [comment]
Thanks for the response. I don't have any experience with Firefox extensions. I will add this to my list of items I can hit up when I have sometime but I don't think that will be anytime soon.

I actually did end up using http://tomi.vanek.sk/ which I found after a bit of Google searching on the same day.
